name = "sef-verify-worker"
main = "src/index.ts"
compatibility_date = "2026-05-27"
workers_dev = true

routes = [
  { pattern = "dlbr.cloud/verify", zone_name = "dlbr.cloud" }
]

[[kv_namespaces]]
binding = "COMPLIANCE_KV"
id = "c23b714b289744a4922b8734a465faa6"
