name = "sef-bridge-frontend"
main = ".output/server/index.mjs"
compatibility_date = "2026-05-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".output/public"
binding = "ASSETS"

[[d1_databases]]
binding = "REGISTAR_DB"
database_name = "sef_centralni_registar"
database_id = "189e8330-f1b4-4172-a9b0-27271acb7847"

[[routes]]
pattern = "sef.dlbr.cloud"
custom_domain = true

[[services]]
binding = "SEF_API"
service = "sef-bridge-backend"
entrypoint = "SEFBackendRPC"
