name = "sef-bridge-backend"
main = "src/index.ts"
compatibility_date = "2026-05-25"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[alias]
"@dlbr/ubl-sdk" = "../ubl-sdk/src/index.ts"
"@sef/shared" = "../shared/index.ts"

[[rules]]
type = "Data"
globs = ["**/*.woff2", "**/*.ttf"]
fallthrough = true

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

[[send_email]]
name = "EMAIL"

[[d1_databases]]
binding = "REGISTAR_DB"
database_name = "sef_centralni_registar"
database_id = "189e8330-f1b4-4172-a9b0-27271acb7847"
migrations_dir = "../../migrations"

[durable_objects]
bindings = [
  { name = "KLIJENT_BAZA_OBJECT", class_name = "KlijentBaza" }
]

[[kv_namespaces]]
binding = "PORESKI_KV"
id = "b688022ffcc247d4843b97d70b76b719"

[[r2_buckets]]
binding = "SEF_UBL_ARHIVA"
bucket_name = "prod-sef-ubl-arhiva-10godina"

[[migrations]]
tag = "v1_init_ledger"
new_sqlite_classes = ["KlijentBaza"]

[ai]
binding = "AI"

[[queues.producers]]
binding = "SEF_QUEUE"
queue = "sef-compliance-queue"

[[queues.producers]]
binding = "OTPREMNICA_QUEUE"
queue = "eotpremnice-reconciliation-queue"

[[queues.producers]]
binding = "WEBHOOK_QUEUE"
queue = "sef-webhook-delivery"

[[queues.consumers]]
queue = "sef-compliance-queue"
max_batch_size = 10
max_batch_timeout = 30

[[queues.consumers]]
queue = "eotpremnice-reconciliation-queue"
max_batch_size = 10
max_batch_timeout = 5

[[queues.consumers]]
queue = "sef-webhook-delivery"
max_batch_size = 10
max_batch_timeout = 5
