name: Builder CI
on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/sef-ci-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install --include=dev
      - name: Run Tests
        run: npm test
